### ISSUE TITLE
Airgap: Cannot detect CSI driver version

### ISSUE THREAD

**Issue by vmwiz** [vmware-tanzu/velero-plugin-for-vsphere#155]
When deploying on an airgapped infrastructure typically container images are fetched from an internal registry.
When `velero-plugin-for-vsphere` starts it try to deduce CSI driver version from the container image tags but fail:

```
2020-08-11T09:50:33.215009344Z velero is running in the namespace, velero
2020-08-11T09:50:33.215056383Z The Image LocalMode: false
2020-08-11T09:50:33.230916361Z Failed to get tag from image gcr.io/cloud-provider-vsphere/csi/release/driver
2020-08-11T09:50:33.230938601Z Failed to get tag from image cloudnativestorage/vsphere-csi
2020-08-11T09:50:33.230941356Z Failed to get tag from image gcr.io/cloud-provider-vsphere/csi/release/syncer
2020-08-11T09:50:33.230943614Z Failed to get tag from image cloudnativestorage/syncer
2020-08-11T09:50:33.230946007Z vSphere CSI driver version is prior to v1.0.2. Velero Plug-in for vSphere requires CSI driver version to be v1.0.2 or above
2020-08-11T09:50:33.239775529Z Using datamanger image vsphereveleroplugin/data-manager-for-plugin:1.0.1.
2020-08-11T09:50:33.254360283Z CustomResourceDefinition/downloads.veleroplugin.io: attempting to create resource
2020-08-11T09:50:33.285626302Z CustomResourceDefinition/downloads.veleroplugin.io: already exists, proceeding
2020-08-11T09:50:33.285637901Z CustomResourceDefinition/downloads.veleroplugin.io: created
2020-08-11T09:50:33.285640934Z CustomResourceDefinition/uploads.veleroplugin.io: attempting to create resource
2020-08-11T09:50:33.316118932Z CustomResourceDefinition/uploads.veleroplugin.io: already exists, proceeding
2020-08-11T09:50:33.316132616Z CustomResourceDefinition/uploads.veleroplugin.io: created
2020-08-11T09:50:33.316135038Z Waiting for resources to be ready in cluster...
2020-08-11T09:50:33.324856874Z DaemonSet/datamgr-for-vsphere-plugin: attempting to create resource
2020-08-11T09:50:33.344802172Z DaemonSet/datamgr-for-vsphere-plugin: already exists, proceeding
2020-08-11T09:50:33.344812003Z DaemonSet/datamgr-for-vsphere-plugin: created
2020-08-11T09:50:33.344814748Z Waiting for data manager daemonset to be ready.
```

These image names are hardcoded in the plugin code https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/d859573753c533507bb485c65370e9404cc7d725/pkg/cmd/utils.go#L139

In my case the images are named `cloud-provider-vsphere/csi/release/driver:v2.0.0` or `myregistry/cloud-provider-vsphere/csi/release/driver:v2.0.0`

**Comment by lintongj** [comment]
@vmwiz 
That is something we need to improve. Currently, to extract CSI driver version, it looks up hardcoded image names, `gcr.io/cloud-provider-vsphere/csi/release/driver` or `cloudnativestorage/vsphere-csi`, for driver and, `gcr.io/cloud-provider-vsphere/csi/release/syncer` or `cloudnativestorage/syncer`, for syncer. 

We will document this issue in https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/master/FAQ.md and fix this issue in master branch. To workaround this issue in air-gapped environment, would you please try to place CSI images under the path, like, `gcr.io/cloud-provider-vsphere/csi/release/` and see if it works for you?

**Comment by vmwiz** [comment]
That doesn't work unfortunately, docker still tries to reach `gcr.io` completely bypassing the `registry-mirror` option we use to simulate a non-airgap environment.

```
Failed to pull image "gcr.io/cloud-provider-vsphere/csi/release/driver:v2.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by lintongj** [comment]
@vmwiz, thanks for the feedback.

Would you please try `cloudnativestorage/vsphere-csi:<version of your choice>` for CSI driver and `cloudnativestorage/syncer:<version of your choice>` for CSI syncer? That is, renaming CSI driver image from `driver` to `vsphere-csi` and placing both CSI driver and syncer images under the path, `cloudnativestorage/`.  Let's see if the workaround works for you.

**Comment by xinyanw409** [comment]
Fix was merged in https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/210.

**Comment by amos-baron** [comment]
this is still an issue for me even after the merged fix. when trying to deploy in an air-gapped environment I get 

> failed to get tag from image cloud-provider-vsphere/csi/release/driver
failed to get tag from image cloud-provider-vsphere/csi/ci/driver
failed to get tag from image cloud-provider-vsphere/csi/release/syncer
failed to get tag from image cloud-provider-vsphere/csi/ci/syncer

**Comment by lintongj** [comment]
Such log message indicates the CSI image name does not come with expected suffix. vSphere plugin internally depends on such suffixes to parse and extra CSI version from CSI image. Even if the CSI image parsing failed, vSphere plugin should still work anyway.

If you have any issue with install velero-plugin-for-vsphere, please feel free to share more context. We will see if there is any bug to fix. Thanks. @amos-baron
